### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/wiki#48]
In #12 I merged the old wiki to the repo.

At that time the desire was for us to publish our documentation via github pages ([see Cassio's comment](https://github.com/singnet/wiki/pull/12#issuecomment-432875036))

This would make an html site available at https://singnet.github.io/wiki - or a custom domain if we create a CNAME file.

We have three options if we still want to do this:

- publish from `docs/` dir, in master branch
- publish from root of master branch
- publish from root of gh-pages branch

I think we should go with the first option, because there are non-documentation files in this repo and I don't know if they will impact the Jekyll build (see below). But this will require reorganising some of the directory structure.

We have two options for the documentation format:

- raw html (ugh, makes it hard to read on github)
- markdown and using Jekyll to generate the html site (my preference)

I'm happy to do this work, but want to make sure it aligns with everyone's expectations.

**Comment by ferrouswheel** [comment]
@IbbyBenali I know you were working on a dev portal of some kind, do you have any thoughts on how this would interoperate with the site I'm proposing based on our technical docs?

**Comment by pennachin** [comment]
Yeah, Ibby has a work in progress dev portal, and these docs will be a subset of it. Please touch base with her (slack is probably better than GitHub issues for that). Doc format should be markdown published with Jekyll or one of the numerous alternatives, never raw HTML. I don't much care where we publish from, but Jekyll allows one to easily exclude files and directories from its build.

**Comment by ferrouswheel** [comment]
wiki repo no longer used.
